@host=http://localhost:8080

### download dmn ###
GET {{host}}/messages http/1.1

### execute with full trace ###
POST {{host}}/messages/dmnresult http/1.1
Content-Type: application/json

{
    "messageId": 10001,
    "messageName": "Asset-AssetType"
}

### validation message ###
POST {{host}}/messages http/1.1
Content-Type: application/json

{
    "messageId": 10001,
    "messageName": "Asset-AssetType"
}

### calculation message ###
POST {{host}}/messages http/1.1
Content-Type: application/json

{
    "messageId": 1002,
    "messageName": "Cash-On-Hand-Ineligible"
}

### no message found ###
POST {{host}}/messages http/1.1
Content-Type: application/json

{
    "messageId": 101,
    "messageName": "test-msg"
}

### no input ###
POST {{host}}/messages http/1.1
Content-Type: application/json

{
    //"messageId": 101,
    //"messageName": "test-msg"
}

### decision service ###
POST {{host}}/messages/getMessageByIdAndName http/1.1
Content-Type: application/json

{
    "messageId": 1002,
    "messageName": "Cash-On-Hand-Ineligible"
}