@host=http://localhost:8080

### download dmn ###
GET {{host}}/Traffic Violation http/1.1

### execute dmn ###
POST {{host}}/Traffic Violation http/1.1
Content-Type: application/json

{
    "Driver": {
        "Points": 2
    },
    "Violation": {
        "Type": "speed",
        "Actual Speed": 120,
        "Speed Limit": 100
    }
}

### execute with full trace ###
POST {{host}}/Traffic Violation/dmnresult http/1.1
Content-Type: application/json

{
    "Driver": {
        "Points": 2
    },
    "Violation": {
        "Type": "speed",
        "Actual Speed": 120,
        "Speed Limit": 100
    }
}

### graceful exit, on no input ###
POST {{host}}/Traffic Violation http/1.1
Content-Type: application/json

{
    //"Driver": {
    //    "Points": 2
    //},
    "Violation": {
        "Type": "speed",
        "Actual Speed": 120,
        "Speed Limit": 100
    }
}

### graceful exit, on no missing data ###
POST {{host}}/Traffic Violation http/1.1
Content-Type: application/json

{
    "Driver": {
        "Points": 2
    },
    "Violation": {
        "Type": "speed",
        //"Actual Speed": 120,
        "Speed Limit": 100
    }
}
